"""
Writes Claude-generated entry function code to importable .py files.

This is architecturally required: run_sweep() uses ProcessPoolExecutor which
pickles entry_fn by module reference. Functions defined via exec() in dynamic
namespaces are NOT picklable. Writing to disk and importing via importlib makes
them picklable as module-level objects that worker processes can re-import.
"""

import ast
import importlib.util
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from agent.config import GENERATED_DIR, PROJECT_DIR

_NAME_PATTERN = re.compile(r'^[a-z][a-z0-9_]{0,60}$')

# review#1 — sandbox auto-loaded Claude code. Only modules in this set may be
# imported by generated strategies. The header already imports numpy + the
# edge_engine helpers; this whitelist guards against e.g. `import subprocess`
# slipping through. Keep this list MINIMAL — adding modules expands the attack
# surface for both malicious and just-buggy Claude output.
_ALLOWED_IMPORT_ROOTS = frozenset({
    'numpy', 'pandas', 'math', 'datetime', 'edge_engine', 'statistics',
})

# Builtins that allow code execution, dynamic import, or filesystem/network
# escape. Banned at the call-site level — the AST validator rejects any
# Call(func=Name(id=X)) for X in this set.
_BANNED_BUILTINS = frozenset({
    'eval', 'exec', 'compile', '__import__', 'open', 'input',
    'breakpoint', 'globals', 'locals', 'vars',
})

# Innocuous dunder attrs Claude might legitimately use.
_ALLOWED_DUNDERS = frozenset({'__class__', '__name__', '__doc__'})


class _SecurityValidator(ast.NodeVisitor):
    """Walk the AST of generated code and collect any forbidden constructs."""

    def __init__(self):
        self.violations: list[str] = []

    def visit_Import(self, node: ast.Import) -> None:
        for alias in node.names:
            root = alias.name.split('.', 1)[0]
            if root not in _ALLOWED_IMPORT_ROOTS:
                self.violations.append(
                    f"forbidden import '{alias.name}' (not in whitelist)"
                )
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        # Relative imports (level > 0) are blocked outright — generated code
        # has no business reaching into agent/ siblings.
        if node.level and node.level > 0:
            self.violations.append("forbidden relative import")
        elif node.module is None:
            self.violations.append("forbidden bare 'from import'")
        else:
            root = node.module.split('.', 1)[0]
            if root not in _ALLOWED_IMPORT_ROOTS:
                self.violations.append(
                    f"forbidden 'from {node.module} import ...' (not in whitelist)"
                )
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Name) and node.func.id in _BANNED_BUILTINS:
            self.violations.append(f"forbidden call to builtin '{node.func.id}'")
        self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> None:
        # Block dunder attribute access (e.g. obj.__builtins__,
        # obj.__globals__, type.__subclasses__) which is the standard escape
        # hatch out of any Python sandbox.
        if (node.attr.startswith('__') and node.attr.endswith('__')
                and node.attr not in _ALLOWED_DUNDERS):
            self.violations.append(f"forbidden dunder access '.{node.attr}'")
        self.generic_visit(node)


def _validate_security(tree: ast.AST) -> None:
    v = _SecurityValidator()
    v.visit(tree)
    if v.violations:
        joined = '; '.join(v.violations)
        raise ValueError(
            f"Generated code rejected by security validator: {joined}. "
            f"Allowed import roots: {sorted(_ALLOWED_IMPORT_ROOTS)}."
        )

_FILE_HEADER = '''\
# AUTO-GENERATED by edge-discovery agent — do not edit manually
# Generated: {timestamp}
# Session:   {session}
import math
import sys
from pathlib import Path

_proj = str(Path(__file__).parent.parent.parent)
if _proj not in sys.path:
    sys.path.insert(0, _proj)

import numpy as np
from edge_engine import (
    spread_gate, rv_size, check_and_fill,
    place_pending, place_oco_pending, has_pending, cancel_pending,
    resolve_risk, PAIR_PIP_SIZE,
)

'''


def _ensure_dirs():
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    init = GENERATED_DIR / "__init__.py"
    if not init.exists():
        init.write_text("# agent generated strategies\n")


def write_entry_module(name: str, code: str, session: str) -> Path:
    """
    Validate and write the entry function to agent/generated/entry_{name}.py.

    Raises:
        ValueError    — name fails pattern check
        SyntaxError   — code is not valid Python
        AttributeError — entry_{name} function not found in AST
    """
    if not _NAME_PATTERN.match(name):
        raise ValueError(
            f"Invalid strategy name '{name}'. "
            f"Must be lowercase letters/digits/underscores, max 60 chars."
        )

    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        raise SyntaxError(f"Syntax error in generated code: {e}") from e

    # review#1 — refuse code that imports outside the whitelist or calls
    # eval/exec/__import__/etc. before it ever reaches disk or sys.modules.
    _validate_security(tree)

    fn_name = f"entry_{name}"
    fn_found = any(
        isinstance(node, ast.FunctionDef) and node.name == fn_name
        for node in ast.walk(tree)
    )
    if not fn_found:
        raise AttributeError(
            f"Function '{fn_name}' not found in generated code. "
            f"Claude must define a function with exactly this name."
        )

    _ensure_dirs()

    header   = _FILE_HEADER.format(
        timestamp=datetime.now(timezone.utc).isoformat(timespec='seconds'),
        session=session,
    )
    path = GENERATED_DIR / f"entry_{name}.py"
    path.write_text(header + code + "\n", encoding='utf-8')
    return path


# review#P2#6 — set of mod_keys currently being loaded by a worker. The
# cleanup path consults this and skips deletion of any in-flight module so
# we don't unlink a .py file mid-import (which raises ModuleNotFoundError
# from inside the worker and kills its task).
_LOADING: set[str] = set()


def load_entry_fn(name: str):
    """
    Load entry_{name} from agent/generated/entry_{name}.py and register it
    in sys.modules so ProcessPoolExecutor worker processes can re-import it
    by dotted path (agent.generated.entry_{name}).

    Raises:
        FileNotFoundError — .py file does not exist
        AttributeError    — function not present after loading
    """
    path    = GENERATED_DIR / f"entry_{name}.py"
    mod_key = f"agent.generated.entry_{name}"

    _LOADING.add(mod_key)
    try:
        spec   = importlib.util.spec_from_file_location(mod_key, path)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        sys.modules[mod_key] = module

        fn_name = f"entry_{name}"
        if not hasattr(module, fn_name):
            raise AttributeError(
                f"Module loaded but '{fn_name}' is not defined. "
                f"Check the generated code for the correct function name."
            )
        return getattr(module, fn_name)
    finally:
        _LOADING.discard(mod_key)


def cleanup_old_modules(keep_n: int = 200):
    """Delete the oldest generated .py files if count exceeds keep_n.

    review#P2#6 — never unlink a module that's currently being loaded by a
    worker (entry in `_LOADING`). The worker would crash mid-import with
    ModuleNotFoundError otherwise.
    """
    _ensure_dirs()
    files = sorted(
        [f for f in GENERATED_DIR.glob("entry_*.py")],
        key=lambda f: f.stat().st_mtime,
    )
    for f in files[:-keep_n] if len(files) > keep_n else []:
        mod_key = f"agent.generated.{f.stem}"
        if mod_key in _LOADING:
            continue   # review#P2#6 — skip in-flight imports
        try:
            f.unlink()
            sys.modules.pop(mod_key, None)
        except OSError:
            pass
